name: Build & Publish Docker On PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from branch
        id: extract_version
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "BRANCH: $BRANCH"
          if [[ "$BRANCH" =~ ^(release|hotfix)/v([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            VERSION="${BASH_REMATCH[2]}"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Branch not compatible for versioning: $BRANCH"
            exit 1
          fi

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sanbricio/go-gallery-front:${{ env.VERSION }}
